spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://192.168.136.129/sell?characterEncoding=utf8&useSSL=true
     username: root
     password: 123456
  jpa:
    hibernate:
      show-sql: true